name: Build
on:
   push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install frontend dependencies
      working-directory: poll-frontend
      run: npm install
      
    - name: Build and copy frontend
      working-directory: poll-frontend
      run: ./gradlew copyWebApp

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build
